name: haskell-yunama
version: 0.1.0.0
github: "Toshiki Amemiya/haskell-yunama"
license: BSD3
author: "Toshiki Amemiya"
maintainer: "am.businessmail.exp@gmail.com"
copyright: "Copyright (c) 2019 Toshiki Amemiya"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Toshiki Amemiya/haskell-yunama#readme>

dependencies:
  - base >= 4.7 && < 5
  - helm
  - cairo
  - pango
  - glib
  - gtk2hs-buildtools
  - brick
  - containers

library:
  source-dirs: src

executables:
  haskell-yunama-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-yunama

tests:
  haskell-yunama-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-yunama
